apiVersion: v1
kind: Pod
metadata:
  name: nginx
  # namespace: nginx
  labels:
    app: nginx
spec:
  # nodeName: gke-myk8s-default-pool-3636d28a-h9bd
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    run: dev